Added new backuping option.
thecsw/memeinvestor_bot pull request #134
Opened 2018-06-28 06:49 UTC by thecsw

This little script will dump the whole database into a backup file with a timestamp. The location of the file is volumed with the main machine.

2018-06-28 15:21 UTC, rickles42 requested changes
Your approach uses `docker-compose run` to launch a new temporary database container and call `mysqldump` on it. I think it might be safer to instead use `docker-compose exec` to just execute `mysqldump` on the real database container. I feel like having two containers accessing the /data/memeinvestor/mysql volume at the same time could lead to problems or at least confusion.

Another question, would it be possible to use `docker copy` to copy the SQL dump file out of the container onto the host, instead of mapping a new volume? Mapping that backups folder means that all the backups are a bit more exposed to the container instead of safe and sound tucked away in a folder on the host. I don't think it's really much of a risk but it seems like keeping the backups out of the hands of the running system is a better approach.

2018-06-29 06:57 UTC, thecsw commented
Sure it is! On it.

2018-06-29 10:24 UTC, thecsw commented
Take a look

2018-06-30 03:19 UTC, rickles42 approved these changes

2018-06-30 03:20 UTC, merged