Dark redesign
thecsw/memeinvestor_bot pull request #172
Opened 2018-07-07 21:02 UTC by robalb

Changes:
- dank redesign
- new pages:
  Leaderboard page
  User page
- splitted js and css in modules, shared by the different pages
- reduced the amount of api calls from index: now it doesn't update when the tab is minimized or out of focus

 Todo
Improve design for the user page, and add other features (show active / old investments, chart of the activities, user badges)

2018-07-07 21:14 UTC, robalb commented
Note: this fixes #157 and part of #146 .
I have tested the website only on firefox for windows
And on chrome for android.
Explorer is not supported

2018-07-08 04:37 UTC, rickles42 requested changes
Looks great overall, just have some minor feedback

2018-07-08 04:37 UTC, rickles42 commented on docs/wall.html
> +            <a href="#" class="brand-logo"><img src="resources/logo240.png" class="logo-img"/><span
Let's have the nav logo and name bring the user back to index.html

2018-07-08 04:37 UTC, rickles42 commented on docs/wall.html
> +        <p>Select one of the market seasons below to view it's top 50 traders.</p>
The purpose of this page is already clear. We can simplify the instructions to "Select a season" or even remove them entirely and just put a label next to the buttons that says, "Season:"

2018-07-08 04:37 UTC, rickles42 commented on docs/wall.html
> +        <h4 class="no-margin-top" >Top Traders wall</h4>
Let's be consistent in the naming of this page, and always call it "Leaderboards"

2018-07-08 04:37 UTC, rickles42 commented on docs/wall.html
> +        <li><a class="grey-text" >leaderboard</a></li>
Change nav to "leaderboards"

2018-07-08 04:37 UTC, rickles42 commented on docs/index.html
> +                        <a href="./wall.html" class="underlined" >view the wall of fame</a>
Change to something like "view full leaderboards"

2018-07-08 04:37 UTC, rickles42 commented on docs/index.html
>                          <p class="overview-text">Active investments: <span id="active-investments">--</span>, detaining
Let's clean up the summary text to three lines:

"Active investments: ---"
"Total invested: --- M¢"
"Total balances: --- M¢"

2018-07-08 04:37 UTC, rickles42 commented on docs/wall.html
> +      <div class="table-wrap" >
Can we clean up the sizing of the leaderboards columns? On my laptop (using Edge browser) there's a bunch of empty space to the right of "Completed investments". Looks like the table should be about 75% of its current width.

2018-07-08 04:39 UTC, rickles42 commented
Also, I got a "INFO: Write your message here" popup when I first launched the page - I feel like we should just remove that bit until we want to push another message"

2018-07-08 07:24 UTC, robalb commented on docs/wall.html
> +      <div class="table-wrap" >
Can you send me a screenshot? Just to see if the problem is related to edge, or your screen dimensions

2018-07-08 07:54 UTC, rickles42 commented on docs/wall.html
> +      <div class="table-wrap" >
@robalb Sent to you on Slack.

2018-07-08 21:19 UTC, robalb commented
ok, i've 
- fixed the logo that didn't link to the index
- cleaned the summary text
- fixed the inconsistency in the leaderboards page naming
- disabled the info popup

the leaderboards table width is a little bit more complicated to fix, i'll do this another time, i also have to add a limit to how much the other pages can stretch horizontally.

2018-07-08 22:17 UTC, rickles42 approved these changes

2018-07-08 22:20 UTC, merged