Added networth to api.
thecsw/memeinvestor_bot pull request #183
Opened 2018-07-14 17:39 UTC by thecsw

I hope it's right!
Closes #182

2018-07-14 18:04 UTC, rickles42 requested changes

2018-07-14 18:04 UTC, rickles42 commented on src/api.py
> +        "networth": int(x.networth),
Should be `sql.networth`

2018-07-15 20:48 UTC, rickles42 approved these changes

2018-07-15 20:51 UTC, rickles42 commented
There's still a problem - it throws an exception now if you try to request a user that doesn't exist. Build and run the bot locally with your change and see if you can figure out a fix

2018-07-16 12:15 UTC, thecsw commented
Okay!

2018-07-18 15:00 UTC, thecsw commented
But shouldn't the sqlalchemy return `False` on error?

``` python
     if not sql:
         return not_found("User not found"
```

2018-07-18 15:02 UTC, rickles42 commented
That is indeed the behavior we want, but it's not occurring. If you test the change locally you'll see that it throws an exception instead.

2018-07-22 08:47 UTC, closed without merging