Add anchor
thecsw/memeinvestor_bot pull request #273
Opened 2018-11-21 19:36 UTC by TheRamenChef

I've noticed a few comments along the lines of:

> !invest 150 MemeCoins

And the bot interprets that as 150 million M¢. This pull request tweaks the regex so that it is interpreted properly.

2018-11-21 22:22 UTC, thecsw commented
Hey! Thank you for the pull request.

When I was testing your branch, it gave me an error (full log below). Please be sure to test your branches before submitting updates. Thanks.

```
INFO:root:New comment ea701kz:
INFO:root: -- retrieved in 105.43s
INFO:root: -- Thecsw: !invest 150 
ERROR:root:invest() takes 6 positional arguments but 7 were given
Traceback (most recent call last):
  File "main.py", line 127, in __call__
    getattr(self, attrname)(sess, comment, *matches.groups())
  File "main.py", line 37, in wrapper
    return fn(self, sess, comment, investor, *args)
TypeError: invest() takes 6 positional arguments but 7 were given
INFO:root: -- processed in  0.85s
INFO:root: -- API calls remaining: 526, resetting in 195s
INFO:root:New comment ea701y5:
INFO:root: -- retrieved in  0.00s
INFO:root: -- Thecsw: !invest 100k
ERROR:root:invest() takes 6 positional arguments but 7 were given
Traceback (most recent call last):
  File "main.py", line 127, in __call__
    getattr(self, attrname)(sess, comment, *matches.groups())
  File "main.py", line 37, in wrapper
    return fn(self, sess, comment, investor, *args)
TypeError: invest() takes 6 positional arguments but 7 were given
INFO:root: -- processed in  0.52s
INFO:root: -- API calls remaining: 525, resetting in 194s
INFO:root:New comment ea7029v:
INFO:root: -- retrieved in  1.80s
INFO:root: -- Thecsw: !invest 100 k
ERROR:root:invest() takes 6 positional arguments but 7 were given
Traceback (most recent call last):
  File "main.py", line 127, in __call__
    getattr(self, attrname)(sess, comment, *matches.groups())
  File "main.py", line 37, in wrapper
    return fn(self, sess, comment, investor, *args)
TypeError: invest() takes 6 positional arguments but 7 were given
INFO:root: -- processed in  0.53s
INFO:root: -- API calls remaining: 521, resetting in 192s
INFO:root:New comment ea702lp:
INFO:root: -- retrieved in  9.40s
INFO:root: -- Thecsw: !invest 100m
ERROR:root:invest() takes 6 positional arguments but 7 were given
Traceback (most recent call last):
  File "main.py", line 127, in __call__
    getattr(self, attrname)(sess, comment, *matches.groups())
  File "main.py", line 37, in wrapper
    return fn(self, sess, comment, investor, *args)
TypeError: invest() takes 6 positional arguments but 7 were given
INFO:root: -- processed in  0.46s
INFO:root: -- API calls remaining: 516, resetting in 182s
INFO:root:New comment ea7032d:
INFO:root: -- retrieved in  9.65s
INFO:root: -- Thecsw: !invest 100m
ERROR:root:invest() takes 6 positional arguments but 7 were given
Traceback (most recent call last):
  File "main.py", line 127, in __call__
    getattr(self, attrname)(sess, comment, *matches.groups())
  File "main.py", line 37, in wrapper
    return fn(self, sess, comment, investor, *args)
TypeError: invest() takes 6 positional arguments but 7 were given
INFO:root: -- processed in  1.03s
INFO:root: -- API calls remaining: 510, resetting in 171s
```

2018-11-21 22:23 UTC, thecsw requested changes
To merge this PR, update the branch code.

2018-11-24 00:32 UTC, TheRamenChef commented
Does it work now?

2018-11-25 17:48 UTC, thecsw commented
Will test it asap

2018-11-25 18:24 UTC, thecsw approved these changes

2018-11-25 18:24 UTC, thecsw commented
Just tested it, everything works! I like it, so now `!invest 100k` will work but `!invest 100kk` will not. We will keep the rules simple without suffix stacking.

Thank you! The PR will be merged and deployed.

2018-11-25 21:27 UTC, merged

2018-11-25 21:31 UTC, thecsw commented
Update deployed and everything is normal. Thank you. Hope to see new updates from you!