demote patch
thecsw/memeinvestor_bot pull request #348
Opened 2019-03-14 18:11 UTC by lukenamop

This adds !demote in src/comment_worker.py and src/message.py

It also addresses the issue of promoting an Executive when there is already a CFO (promotes them straight to COO now), and does the same with the reciprocal demotions.

Tests all new and changed !promote and !demote inputs in test/firms.py

Also addresses a few unrelated issues in test/invest.py and test/active.py

2019-03-14 19:43 UTC, thecsw reviewed
I took a quick glance at the changes, seems fine! Don't forget to add `!demote` command to the list of commands in `!help`. Expect this to be reviewed within several hours/days.

2019-03-14 22:19 UTC, lukenamop commented
@thecsw Good catch, I added that in 👍

2019-03-16 10:22 UTC, lukenamop commented
@thecsw I also was informed last night that '!tax' was not included in the help command, so I added that this morning.

2019-03-16 22:54 UTC, thecsw requested changes
I left some comments in the code about logical statements and commenting. Please feel free to dispute any of those. Thanks

2019-03-16 22:54 UTC, thecsw commented on src/comment_worker.py
> +        if user_role == "":
Unnecessary "elif" after "return" [no-else-return]

There is only a return statement in this branch.

2019-03-16 22:54 UTC, thecsw commented on src/comment_worker.py
> +        elif user_role == "assoc":
Line 718, 725, 737, 749 you have `elif` statements whan you can have just a simple `if` statement.

By the logic, you don't have a final set of instructions to execute, so all `elif`s can be changed into if.

2019-03-16 22:54 UTC, thecsw commented on src/comment_worker.py
> +    def demote(self, sess, comment, investor, to_demote):
Can you also add some comments in your code? I am not asking for docstrings or official Sphinx kind of documentation. Just inline comments. For example,

``` python
if user_role == "":
 ...
```

Can be turned into 

``` python
# If investor is already at the lowest rank (floor trader), we can't demote him.
if user_role == "":
 ...
```

And something like that. Currently, I plan to sprinkle the code with inline commenting and docstrings so we can start forming an official documentation for the code. Thanks

2019-03-16 22:54 UTC, thecsw commented on src/comment_worker.py
> +            if investor.firm_role != "ceo":
Yeah, just refer to the previous comment about in-code documentation.

2019-03-16 22:54 UTC, thecsw commented on src/comment_worker.py
> +        if user.firm_role == "ceo":
Probably all `elif`s here can be changed into simple `if`s

2019-03-16 22:54 UTC, thecsw commented on src/message.py
> +The minimum possible investment is %MIN% MemeCoins (1% of your balance) or 100 memecoins, whatever is higher.
Good catch!

2019-03-16 22:54 UTC, thecsw commented on test/firms.py
> +    def test_promote_self(self):
I like your testing habits. Keep it up!

2019-03-16 22:56 UTC, thecsw commented on src/comment_worker.py
> +    def demote(self, sess, comment, investor, to_demote):
Also yeah, depending on your IDE, if you have a big/long comment, break it down to several lines. Usually every comment line is no longer than 80 characters.

2019-03-16 22:56 UTC, thecsw commented on src/comment_worker.py
> +    def demote(self, sess, comment, investor, to_demote):
``` python
# This is a multiline comment. This is a very big comment that looks weird so
# I have to break it down. Thank you for your attention.

2019-03-25 13:10 UTC, lukenamop commented
Working on the requested changes now! Finally got some free time.

2019-03-25 13:28 UTC, lukenamop commented
@thecsw Okay, I've made the changes and added comments to my code :)

2019-03-31 17:12 UTC, thecsw approved these changes
Tested and it looks good to me. Good job! Approved.

2019-03-31 17:18 UTC, merged