Change bot replies to reflect new caps
thecsw/memeinvestor_bot pull request #401
Opened 2019-05-22 17:51 UTC by Dracologist

I decided to try to change the standard investment confirmation to include how many times you've invested in that post and the maximum number of invest in the same post. I also tried to make the rejection message for investments above the maximum amount more informative. 

Please check my code thoroughly because my only real experience with Python before this was a "Programming 101" class I took 6 years ago while I was in Running Start

2019-05-22 19:27 UTC, Dracologist commented
I decided to try my hand at creating commands to automatically invest the minimum or maximum amount of MemeCoins allowed because why not? If nothing else, it's decent practice for me to learn more about Python

2019-05-22 20:18 UTC, Dracologist commented
I'm just adding small quality of life features me and people from my firm think might be cool because this is fun. Feel free to reject any changes you don't like

2019-05-26 01:59 UTC, thecsw requested changes
I like the PR update and making the new feature more agile. So, here is the list of changes I think would be nice:
 - I am not sure we need to have max/min in the regex
 - There are some empty lines in `message.py`

2019-05-26 01:59 UTC, thecsw commented on src/comment_worker.py
> +            matches = reg.fullmatch(re.sub(r"![Ii]\s+", "!invest ", comment.body.strip()))
Why are you manually setting this here?

2019-05-26 01:59 UTC, thecsw commented on src/message.py
> +
Too many empty lines!

2019-05-26 02:29 UTC, thecsw reviewed
If we set the limit to 50%, they could do just 50%

Money investing is not a casino where you can just go *max* or *ALL IN*. That is why we never made `!invest all` or `!all`, it just doesn't make sense in a economical situtation. 

If you have thoughts about this, I would love to chat

2019-05-26 02:35 UTC, Dracologist commented
I'm pretty sure real-life investing doesn't have any limit to how much of your money you're allowed to invest in a single stock either, but doing so is probably going to improve r/MemeEconomy for most users. That's kinda my logic behind the `max` thing

2019-05-27 18:53 UTC, HarryjosephDevelopment commented
What else is wrong with this pr?

2019-05-27 18:57 UTC, thecsw approved these changes
Seems fine to me! This PR is approved. It will be merged if the mods or r/MemeEconomy decide to or when we start a new season with bonding stocks update. Thank you!

2019-05-27 18:58 UTC, thecsw commented
@HarryjosephDevelopment Everything seems fine. Just approved it.

2019-05-27 18:58 UTC, HarryjosephDevelopment commented
> @HarryjosephDevelopment Everything seems fine. Just approved it.

Sounds good! Is there a list of updates which will come out in the next season?

2019-05-27 19:00 UTC, thecsw commented
@HarryjosephDevelopment the dream is to implement the stocks update from #373 and implement the codebase in Go instead of Python #394 

Also, @Keanu73 and I are talking about a possibility of rebuilding the bot with JS, see #394 for more details

2019-05-27 19:32 UTC, luisbg commented
I like this a lot more than the original PR 😄

2019-05-27 19:34 UTC, luisbg commented
> Also, @Keanu73 and I are talking about a possibility of rebuilding the bot with JS, see #394 for more details

What are the benefits of rebuilding in JS? I'm curious.

2019-06-01 23:25 UTC, thecsw commented
Just to clarify, the changes are approved but they *WILL NOT* be merged until the necessity comes.

2019-06-02 21:28 UTC, closed without merging